markdown: redcarpet
paginate: 30
paginate_path: ":num"
pygments: true
permalink: /:title/

name: DevGrow.com
title: "DevGrow - Design, Develop, Grow"
author: DevGrow.com
description: "Online journal dedicated to providing resources on the design, development and growth of websites"
url: http://devgrow.com

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'Capfile', 'Guardfile']

authors:
  mdolon:
    display_name: "Monji Dolon"
    pic: "/assets/images/authors/mdolon.jpg"
    email: "mdolon@gmail.com"
    web: "http://www.mdolon.com/"
    twitter: "mdolon"
    github: "mdolon"
    bio: "Monji is a product designer and front-end developer.  In his free time, he likes to play guitar, climb tall mountains and go surfing.  You can find his portfolio at <a href='http://mdolon.com/'>mdolon.com</a>."
  carno:
    display_name: "Christian Arno"
    web: "http://usa.lingo24.com/"
    pic: "http://devgrow.s3.amazonaws.com/assets/images/global_audience-author.png"
    bio: "<a title='Author: Christian Arno on Google+' href='https://plus.google.com/+ChristianArno' rel='author' target='_blank'>Christian Arno</a> is the Managing Director of Lingo24. Visit Christian's website at <a href='http://www.lingo24us.com/'>www.lingo24us.com</a>. Follow Lingo24 on <a href='https://twitter.com/lingo24'>Twitter</a>"
